const GRAPH_VERSION = "v26.0";
const TRANSCRIBE_MODEL = "@cf/openai/whisper-large-v3-turbo";

const NUMEROS = {um:1,uma:1,dois:2,duas:2,tres:3,quatro:4,cinco:5,seis:6,sete:7,oito:8,nove:9,dez:10,onze:11,doze:12,treze:13,quatorze:14,quinze:15,dezesseis:16,dezessete:17,dezoito:18,dezenove:19,vinte:20};
const ALIASES_CLIENTES = [["marcelo caldo de cana","Marcelo 1"],["caldo de cana","Marcelo 1"],["marcelo 2","Marcelo 2"],["marcelo cosmos","Marcelo 2"],["padaria paciencia","Padaria Paciência"],["barraca condominio","Barraca Condomínio"],["condominio","Barraca Condomínio"],["padaria","Padaria BMG"],["peixaria tiago","Tiago"],["peixaria para","Pará"],["sr gilson","Seu Gilson"],["senhor gilson","Seu Gilson"],["gilson","Seu Gilson"],["chop feira","Chop Feira"]];

function corsHeaders(){return {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"};}
function json(data,init={}){return new Response(JSON.stringify(data),{...init,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders(),...(init.headers||{})}});}
function normalizar(t=""){return String(t).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();}
function primeiroNumero(texto){const t=normalizar(texto);const d=t.match(/\b(\d+)\b/);if(d)return Number(d[1]);for(const [p,v] of Object.entries(NUMEROS)){if(new RegExp(`\\b${p}\\b`).test(t))return v;}return null;}
function numeroAntesDe(texto,termo){const t=normalizar(texto);const pn=Object.keys(NUMEROS).join("|");const m=t.match(new RegExp(`(?:\\b(\\d+)\\b|\\b(${pn})\\b)(?:\\s+sacos?)?\\s+(?:de\\s+)?${termo}`));if(!m)return null;return m[1]?Number(m[1]):NUMEROS[m[2]];}
function identificarCliente(texto){const t=normalizar(texto);for(const [a,c] of ALIASES_CLIENTES)if(t.includes(a))return c;return null;}
function parseVenda(texto){const original=String(texto||"").trim(),t=normalizar(original),cliente=identificarCliente(original);let pagamento="Não informado";if(/\bfiado\b/.test(t))pagamento="Fiado";else if(/\bpix\b/.test(t))pagamento="PIX";else if(/\bpago\b|\bdinheiro\b/.test(t))pagamento="Dinheiro";let filtrado=numeroAntesDe(original,"filtrado(?:s)?"),escamas=numeroAntesDe(original,"escamas?");const tf=/\bfiltrado(?:s)?\b/.test(t),te=/\bescamas?\b/.test(t);if(filtrado==null&&escamas==null){const q=primeiroNumero(original);if(q!=null){if(tf&&!te)filtrado=q;else escamas=q;}}filtrado=filtrado||0;escamas=escamas||0;const total=filtrado+escamas;return {cliente,escamas,filtrado,quantidade_total:total,pagamento,texto_original:original,status:"pendente_revisao",confianca:cliente&&total>0?"alta":"revisar"};}

async function getWhatsAppMediaInfo(id,token){const r=await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Falha ao consultar mídia na Meta: HTTP ${r.status}`);return r.json();}
async function downloadWhatsAppMedia(url,token){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Falha ao baixar mídia da Meta: HTTP ${r.status}`);return r.arrayBuffer();}
function arrayBufferToBase64(ab){const b=new Uint8Array(ab);let s="";for(let i=0;i<b.length;i+=0x8000)s+=String.fromCharCode(...b.subarray(i,Math.min(i+0x8000,b.length)));return btoa(s);}
async function transcreverAudio(env,ab){if(!env.AI)throw new Error("binding AI não disponível");const r=await env.AI.run(TRANSCRIBE_MODEL,{audio:arrayBufferToBase64(ab),task:"transcribe",language:"pt",vad_filter:true,initial_prompt:"Vendas de gelo no Rio de Janeiro. Preserve nomes de clientes, quantidades, PIX, dinheiro, fiado, escamas e filtrado."});return String(r?.text||"").trim();}
function chaveMensagem(r){return `mensagem:${r.mensagem_id||`sem-id-${Date.now()}`}`;}
async function salvarMensagemNoKV(env,r){if(!env.VENDAS)return null;const k=chaveMensagem(r);await env.VENDAS.put(k,JSON.stringify({...r,status:"pendente",recebido_em:new Date().toISOString()}));return k;}
async function atualizarMensagemNoKV(env,k,a){if(!env.VENDAS||!k)return;const atual=await env.VENDAS.get(k,{type:"json"})||{};await env.VENDAS.put(k,JSON.stringify({...atual,...a,atualizado_em:new Date().toISOString()}));}
async function aplicarParserNoKV(env,k,t){const venda=parseVenda(t);await atualizarMensagemNoKV(env,k,{venda,status:"pendente_revisao",parseado_em:new Date().toISOString()});return venda;}

function itensVendaDoRegistro(key,reg){const v=reg?.venda;if(!v||!v.cliente)return[];const base={remote_key:key,transcricao:reg.transcricao||reg.texto||v.texto_original||"",recebido_em:reg.recebido_em||reg.criado_em||reg.parseado_em||"",pagamento:v.pagamento||"Não informado",confianca:v.confianca||"revisar",status_itens:reg.status_itens||{}};const itens=[];if(Number(v.escamas)>0&&base.status_itens[`${key}:esc`]!="confirmada_app"&&base.status_itens[`${key}:esc`]!="ignorada_app")itens.push({...base,remote_id:`${key}:esc`,cliente:v.cliente,qtd:Number(v.escamas),tipo:"esc"});if(Number(v.filtrado)>0&&base.status_itens[`${key}:filt`]!="confirmada_app"&&base.status_itens[`${key}:filt`]!="ignorada_app")itens.push({...base,remote_id:`${key}:filt`,cliente:v.cliente,qtd:Number(v.filtrado),tipo:"filt"});return itens;}
async function listarInbox(env){if(!env.VENDAS)return[];const out=[];let cursor;do{const p=await env.VENDAS.list({prefix:"mensagem:",cursor,limit:100});for(const k of p.keys){const reg=await env.VENDAS.get(k.name,{type:"json"});if(!reg||reg.status!=="pendente_revisao")continue;out.push(...itensVendaDoRegistro(k.name,reg));}cursor=p.list_complete?undefined:p.cursor;}while(cursor);out.sort((a,b)=>String(b.recebido_em).localeCompare(String(a.recebido_em)));return out;}

export default {async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders()});
if(request.method==="GET"&&url.pathname==="/api/inbox"){try{return json({ok:true,vendas:await listarInbox(env),atualizado_em:new Date().toISOString()});}catch(e){return json({ok:false,erro:String(e)},{status:500});}}
if(request.method==="POST"&&url.pathname==="/api/inbox/status"){try{const b=await request.json(),key=String(b?.remote_key||""),remoteId=String(b?.remote_id||""),status=String(b?.status||"");if(!key.startsWith("mensagem:")||!remoteId.startsWith(key+":"))return json({ok:false,erro:"Chave inválida"},{status:400});if(!["confirmada_app","ignorada_app"].includes(status))return json({ok:false,erro:"Status inválido"},{status:400});const reg=await env.VENDAS.get(key,{type:"json"})||{},map={...(reg.status_itens||{}),[remoteId]:status};await atualizarMensagemNoKV(env,key,{status_itens:map,status_app_em:new Date().toISOString()});return json({ok:true});}catch(e){return json({ok:false,erro:String(e)},{status:500});}}
if(request.method==="GET"){const mode=url.searchParams.get("hub.mode"),token=url.searchParams.get("hub.verify_token"),challenge=url.searchParams.get("hub.challenge");if(mode==="subscribe"&&env.WEBHOOK_VERIFY_TOKEN&&token===env.WEBHOOK_VERIFY_TOKEN)return new Response(challenge,{status:200,headers:{"Content-Type":"text/plain"}});return new Response("Token de verificação inválido",{status:403});}
if(request.method==="POST"){try{const body=await request.json(),value=body?.entry?.[0]?.changes?.[0]?.value,message=value?.messages?.[0],contact=value?.contacts?.[0];if(message){const resumo={tipo:message.type||"desconhecido",remetente:message.from||contact?.wa_id||"desconhecido",nome:contact?.profile?.name||"",mensagem_id:message.id||"",texto:message.text?.body||"",audio_id:message.audio?.id||"",audio_mime_type:message.audio?.mime_type||"",audio_voz:message.audio?.voice===true};let k=null;try{k=await salvarMensagemNoKV(env,resumo);}catch(e){console.log(String(e));}if(message.type==="text"&&resumo.texto){try{await aplicarParserNoKV(env,k,resumo.texto);}catch(e){console.log(String(e));}}if(message.type==="audio"&&message.audio?.id){if(!env.META_ACCESS_TOKEN){try{await atualizarMensagemNoKV(env,k,{status:"aguardando_token_meta"});}catch(e){console.log(String(e));}}else{try{const mi=await getWhatsAppMediaInfo(message.audio.id,env.META_ACCESS_TOKEN);if(mi.url){const ab=await downloadWhatsAppMedia(mi.url,env.META_ACCESS_TOKEN);await atualizarMensagemNoKV(env,k,{status:"audio_baixado",audio_bytes:ab.byteLength,audio_mime_type:mi.mime_type||message.audio?.mime_type||"",audio_file_size_meta:mi.file_size||null,audio_baixado_em:new Date().toISOString()});try{await atualizarMensagemNoKV(env,k,{status:"transcrevendo_audio"});const t=await transcreverAudio(env,ab);await atualizarMensagemNoKV(env,k,{status:"transcrito",texto:t,transcricao:t,modelo_transcricao:TRANSCRIBE_MODEL,transcrito_em:new Date().toISOString()});await aplicarParserNoKV(env,k,t);}catch(e){await atualizarMensagemNoKV(env,k,{status:"erro_transcricao",erro_transcricao:String(e)});}}}catch(e){try{await atualizarMensagemNoKV(env,k,{status:"erro_audio_meta",erro_audio:String(e)});}catch(_){}}}}}return new Response("EVENT_RECEIVED",{status:200});}catch(e){console.log(String(e));return new Response("EVENT_RECEIVED",{status:200});}}
return new Response("Webhook Gelo Tutóia ativo",{status:200});}};
