import { interpretarVenda } from "./parser.js";
const VERIFY_TOKEN="gelo-tutoia-2026",GRAPH_VERSION="v26.0",TRANSCRIBE_MODEL="@cf/openai/whisper-large-v3-turbo",CONFIG_KEY="config:clientes";
function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Cache-Control":"no-store"}}
function json(data,init={}){return new Response(JSON.stringify(data),{...init,headers:{"Content-Type":"application/json; charset=utf-8",...corsHeaders(),...(init.headers||{})}})}
function somenteDigitos(v=""){return String(v).replace(/\D/g,"")}
function remetenteAutorizado(env,r){const raw=String(env.AUTHORIZED_SENDERS||"").trim();if(!raw)return true;return raw.split(/[\s,;]+/).map(somenteDigitos).filter(Boolean).includes(somenteDigitos(r))}
async function getConfig(env){return env.VENDAS?await env.VENDAS.get(CONFIG_KEY,{type:"json"}):null}
async function putConfig(env,b){if(!env.VENDAS)throw new Error("KV indisponível");const clientes=Array.isArray(b?.clientes)?b.clientes.filter(x=>x&&String(x.nome||"").trim()).map(x=>({nome:String(x.nome).trim(),preco_esc:Number(x.preco_esc)||0,preco_filt:Number(x.preco_filt)||0,tipo:["escamas","filtrado","ambos"].includes(x.tipo)?x.tipo:"ambos",apelidos:Array.isArray(x.apelidos)?x.apelidos.map(a=>String(a).trim()).filter(Boolean).slice(0,30):[]})):[];await env.VENDAS.put(CONFIG_KEY,JSON.stringify({clientes,atualizado_em:new Date().toISOString()}));return clientes}
async function getWhatsAppMediaInfo(id,token){const r=await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Falha ao consultar mídia na Meta: HTTP ${r.status}`);return r.json()}
async function downloadWhatsAppMedia(url,token){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Falha ao baixar mídia da Meta: HTTP ${r.status}`);return r.arrayBuffer()}
function arrayBufferToBase64(a){const b=new Uint8Array(a);let s="";for(let i=0;i<b.length;i+=0x8000)s+=String.fromCharCode(...b.subarray(i,Math.min(i+0x8000,b.length)));return btoa(s)}
async function transcreverAudio(env,a){if(!env.AI)throw new Error("binding AI não disponível");const r=await env.AI.run(TRANSCRIBE_MODEL,{audio:arrayBufferToBase64(a),task:"transcribe",language:"pt",vad_filter:true,initial_prompt:"Vendas de gelo Gelo Tutóia. Preserve nomes e apelidos dos clientes, quantidades, PIX, dinheiro, fiado, escamas e filtrado."});return String(r?.text||"").trim()}
function chaveMensagem(id){return`mensagem:${id||`sem-id-${Date.now()}`}`}
async function salvar(env,key,dados){if(!env.VENDAS||!key)return;const atual=await env.VENDAS.get(key,{type:"json"})||{};await env.VENDAS.put(key,JSON.stringify({...atual,...dados,atualizado_em:new Date().toISOString()}))}
async function interpretar(env,key,texto){const venda=interpretarVenda(texto,await getConfig(env));await salvar(env,key,{status:"venda_interpretada",venda,interpretado_em:new Date().toISOString()});console.log("Gelo Tutóia - venda interpretada:",JSON.stringify(venda))}
function itensVendaDoRegistro(key,reg){const v=reg?.venda;if(!v||!v.cliente)return[];const st=reg.status_itens||{},base={remote_key:key,transcricao:reg.transcricao||reg.texto||v.texto_origem||"",recebido_em:reg.recebido_em||reg.interpretado_em||reg.atualizado_em||"",pagamento:v.pagamento||"Não informado",confianca:v.precisa_revisao?"revisar":"alta"},out=[];for(const[tipo,q,suf]of[["esc",v.escamas,"esc"],["filt",v.filtrado,"filt"]]){const id=`${key}:${suf}`;if(Number(q)>0&&!["confirmada_app","ignorada_app"].includes(st[id]))out.push({...base,remote_id:id,cliente:v.cliente,qtd:Number(q),tipo})}return out}
async function listarInbox(env){if(!env.VENDAS)return[];const out=[];let cursor;do{const p=await env.VENDAS.list({prefix:"mensagem:",cursor,limit:100});for(const k of p.keys){const r=await env.VENDAS.get(k.name,{type:"json"});if(r?.venda)out.push(...itensVendaDoRegistro(k.name,r))}cursor=p.list_complete?undefined:p.cursor}while(cursor);return out.sort((a,b)=>String(b.recebido_em).localeCompare(String(a.recebido_em)))}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders()});
if(request.method==="GET"&&url.pathname==="/api/clientes"){try{return json({ok:true,config:await getConfig(env)})}catch(e){return json({ok:false,erro:String(e)},{status:500})}}
if(request.method==="POST"&&url.pathname==="/api/clientes"){try{return json({ok:true,clientes:await putConfig(env,await request.json())})}catch(e){return json({ok:false,erro:String(e)},{status:400})}}
if(request.method==="GET"&&url.pathname==="/api/inbox"){try{return json({ok:true,vendas:await listarInbox(env),atualizado_em:new Date().toISOString()})}catch(e){return json({ok:false,erro:String(e)},{status:500})}}
if(request.method==="POST"&&url.pathname==="/api/inbox/status"){try{const b=await request.json(),key=String(b?.remote_key||""),id=String(b?.remote_id||""),status=String(b?.status||"");if(!key.startsWith("mensagem:")||!id.startsWith(key+":"))return json({ok:false,erro:"Chave inválida"},{status:400});if(!["confirmada_app","ignorada_app"].includes(status))return json({ok:false,erro:"Status inválido"},{status:400});const reg=await env.VENDAS.get(key,{type:"json"})||{};await salvar(env,key,{status_itens:{...(reg.status_itens||{}),[id]:status},status_app_em:new Date().toISOString()});return json({ok:true})}catch(e){return json({ok:false,erro:String(e)},{status:500})}}
if(request.method==="GET"){const mode=url.searchParams.get("hub.mode"),token=url.searchParams.get("hub.verify_token"),challenge=url.searchParams.get("hub.challenge");if(mode==="subscribe"&&token===VERIFY_TOKEN)return new Response(challenge,{status:200,headers:{"Content-Type":"text/plain"}});return new Response("Token de verificação inválido",{status:403})}
if(request.method==="POST"){try{const body=await request.json(),value=body?.entry?.[0]?.changes?.[0]?.value,message=value?.messages?.[0],contact=value?.contacts?.[0];if(!message)return new Response("EVENT_RECEIVED",{status:200});const remetente=message.from||contact?.wa_id||"desconhecido";if(!remetenteAutorizado(env,remetente))return new Response("EVENT_RECEIVED",{status:200});const key=chaveMensagem(message.id),resumo={tipo:message.type||"desconhecido",remetente,nome:contact?.profile?.name||"",mensagem_id:message.id||"",texto:message.text?.body||"",audio_id:message.audio?.id||"",audio_mime_type:message.audio?.mime_type||"",audio_voz:message.audio?.voice===true,status:"pendente",recebido_em:new Date().toISOString()};await salvar(env,key,resumo);if(message.type==="text"&&resumo.texto){try{await interpretar(env,key,resumo.texto)}catch(e){await salvar(env,key,{status:"erro_parser",erro_parser:String(e)})}}if(message.type==="audio"&&message.audio?.id){if(!env.META_ACCESS_TOKEN)await salvar(env,key,{status:"aguardando_token_meta"});else try{const media=await getWhatsAppMediaInfo(message.audio.id,env.META_ACCESS_TOKEN);if(media.url){const audio=await downloadWhatsAppMedia(media.url,env.META_ACCESS_TOKEN);await salvar(env,key,{status:"audio_baixado",audio_bytes:audio.byteLength});try{const texto=await transcreverAudio(env,audio);await salvar(env,key,{status:"transcrito",texto,transcricao:texto,modelo_transcricao:TRANSCRIBE_MODEL,transcrito_em:new Date().toISOString()});await interpretar(env,key,texto)}catch(e){await salvar(env,key,{status:"erro_transcricao",erro_transcricao:String(e)})}}}catch(e){await salvar(env,key,{status:"erro_audio_meta",erro_audio:String(e)})}}return new Response("EVENT_RECEIVED",{status:200})}catch(e){console.log("Gelo Tutóia - erro no webhook:",String(e));return new Response("EVENT_RECEIVED",{status:200})}}
return new Response("Webhook Gelo Tutóia ativo",{status:200})}}
